### ISSUE TITLE
Definir scope del proyecto a.k.a la lista de features

### ISSUE THREAD

**Issue by Xabadu** [Xabadu/jorgitos-chat#1]
El chat deberia tener:

- Una pantalla principal del chat que deberia tener:
  - Un area que muestre todos los mensajes que han llegado al chat
  - Un input para escribir mensajes y un boton para enviarlos
  - Una lista de usuarios que estan conectados al chat
- Una pantalla de lobby del chat que tenga:
  - Un input para que el usuario ponga el nombre que quiere usar en el chat

**Comment by arroadie** [comment]
> Un input para que el usuario ponga el nombre que quiere usar en el chat
Usuarios son unicos?

**Comment by enBonnet** [comment]
Si totalmente @arroadie
