### ISSUE TITLE
Feature: Agregar zumbidos imitando al antiguo MSN

### ISSUE THREAD

**Issue by ZeegCL** [Xabadu/jorgitos-chat#11]
Sería entretenido agregar un botón que envíe un zumbido al canal de chat, como lo tenía el difunto MSN. La ventana podría vibrar usando animaciones CSS y a la vez reproducir un sonido. En navegadores mobile podría implementarse la Vibration API (https://developer.mozilla.org/en-US/docs/Web/API/Vibration_API).

Video para recordar los viejos tiempos: https://www.youtube.com/watch?v=Y36wN4KGymc
Sonido del zumbido: https://www.youtube.com/watch?v=iSVm2ORr8cg

Extra points: agregar un límite a la cantidad de zumbidos que se puede enviar por minuto.

**Comment by ZeegCL** [comment]
Aquí el snippet para el efecto shake en CSS: https://css-tricks.com/snippets/css/shake-css-keyframe-animation/

**Comment by ZeegCL** [comment]
Primer intento #21

**Comment by Xabadu** [comment]
Agregado via #21 y #26
